export const IDENTITIES = {
  caseManager: {
    id: 'caseManager',
    label: 'Gestor de casos',
    subjectId: 'case-manager-1',
    subjectType: 'HUMAN',
    roles: ['case-manager'],
    description: 'Abre, consulta e cancela casos.',
  },
  documentProcessor: {
    id: 'documentProcessor',
    label: 'Processador documental',
    subjectId: 'document-processor-1',
    subjectType: 'WORKLOAD',
    roles: ['document-processor'],
    description: 'Registra e consulta documentos.',
  },
  analyst: {
    id: 'analyst',
    label: 'Analista operacional',
    subjectId: 'operations-analyst-1',
    subjectType: 'HUMAN',
    roles: ['operations-analyst'],
    description: 'Consulta evidências e executa investigações.',
  },
  decisionAgent: {
    id: 'decisionAgent',
    label: 'Agente de decisão',
    subjectId: 'decision-agent-1',
    subjectType: 'WORKLOAD',
    roles: ['decision-agent'],
    description: 'Cria recomendações fundamentadas.',
  },
  approver: {
    id: 'approver',
    label: 'Aprovador humano',
    subjectId: 'approver-1',
    subjectType: 'HUMAN',
    roles: ['approver'],
    description: 'Decide conforme alçada e segregação de funções.',
  },
  executionService: {
    id: 'executionService',
    label: 'Serviço de execução',
    subjectId: 'execution-service',
    subjectType: 'WORKLOAD',
    roles: ['execution-service'],
    description: 'Solicita comandos governados e idempotentes.',
  },
  reconciler: {
    id: 'reconciler',
    label: 'Reconciliador',
    subjectId: 'reconciler-1',
    subjectType: 'HUMAN',
    roles: ['reconciler'],
    description: 'Resolve execuções com resultado ambíguo.',
  },
  auditor: {
    id: 'auditor',
    label: 'Auditor',
    subjectId: 'auditor-1',
    subjectType: 'HUMAN',
    roles: ['auditor'],
    description: 'Consulta timeline, evidências e execuções.',
  },
}

export const ACTION_IDENTITIES = {
  createCase: 'caseManager',
  listCases: 'caseManager',
  readCase: 'caseManager',
  cancelCase: 'caseManager',
  registerDocument: 'documentProcessor',
  readEvidence: 'analyst',
  investigate: 'analyst',
  recommend: 'decisionAgent',
  approve: 'approver',
  execute: 'executionService',
  readExecution: 'auditor',
  reconcile: 'reconciler',
  timeline: 'auditor',
}

export const IDENTITY_OPTIONS = Object.values(IDENTITIES)
