export const IDENTITIES = {
  caseManager: {
    id: 'caseManager',
    label: 'Gestor de casos',
    subjectId: 'case-manager-1',
    subjectType: 'HUMAN',
    role: 'case-manager',
    description: 'Abre casos e agenda operações do processo.',
  },
  documentProcessor: {
    id: 'documentProcessor',
    label: 'Processador documental',
    subjectId: 'document-processor-1',
    subjectType: 'WORKLOAD',
    role: 'document-processor',
    description: 'Registra documentos e evidências sintéticas.',
  },
  analyst: {
    id: 'analyst',
    label: 'Analista operacional',
    subjectId: 'operations-analyst-1',
    subjectType: 'HUMAN',
    role: 'operations-analyst',
    description: 'Executa a investigação e consulta evidências.',
  },
  decisionAgent: {
    id: 'decisionAgent',
    label: 'Agente de decisão',
    subjectId: 'decision-agent-1',
    subjectType: 'WORKLOAD',
    role: 'decision-agent',
    description: 'Produz recomendação, sem aprovar ou executar.',
  },
  approver: {
    id: 'approver',
    label: 'Aprovador humano',
    subjectId: 'approver-1',
    subjectType: 'HUMAN',
    role: 'approver',
    description: 'Decide conforme alçada e segregação de funções.',
  },
  executionService: {
    id: 'executionService',
    label: 'Serviço de execução',
    subjectId: 'execution-service',
    subjectType: 'WORKLOAD',
    role: 'execution-service',
    description: 'Executa comando mock com idempotência.',
  },
  reconciler: {
    id: 'reconciler',
    label: 'Reconciliador',
    subjectId: 'reconciler-1',
    subjectType: 'HUMAN',
    role: 'reconciler',
    description: 'Resolve resultados ambíguos após consulta determinística.',
  },
  auditor: {
    id: 'auditor',
    label: 'Auditor',
    subjectId: 'auditor-1',
    subjectType: 'HUMAN',
    role: 'auditor',
    description: 'Consulta timeline e evidências minimizadas.',
  },
  operator: {
    id: 'operator',
    label: 'Operador da plataforma',
    subjectId: 'platform-operator-1',
    subjectType: 'HUMAN',
    role: 'platform-operator',
    description: 'Inspeciona outbox, timers, projeções e dead letters.',
  },
}

export const ACTION_IDENTITIES = {
  createCase: 'caseManager',
  readCase: 'caseManager',
  registerDocument: 'documentProcessor',
  investigate: 'analyst',
  recommend: 'decisionAgent',
  approve: 'approver',
  execute: 'executionService',
  readExecution: 'reconciler',
  reconcile: 'reconciler',
  timeline: 'auditor',
  operations: 'operator',
}

export const IDENTITY_OPTIONS = Object.values(IDENTITIES)
